import Config from 'react-native-config';

export const STT_CONFIG = {
  BASE_URL: Config.AZURE_FUNCTION_BASE_URL ?? '',
  UPLOADS_PREPARE_KEY: Config.AZURE_UPLOADS_PREPARE_KEY ?? '',
  UPLOAD_COMPLETE_KEY: Config.AZURE_UPLOAD_COMPLETE_KEY ?? '',
  PROCESSED_STATUS_KEY: Config.AZURE_PROCESSED_STATUS_KEY ?? '',
  PROCESSED_TRANSCRIPT_KEY: Config.AZURE_PROCESSED_TRANSCRIPT_KEY ?? '',
};
